// Code generated by github.com/ARUMANDESU/gobuildergen. DO NOT EDIT.
package example

import (
    "time"
    examplepackage "githab.com/ARUMANDESU/gobuildergen/example/example-package"
)

type ExampleStructBuilder struct {
    val ExampleStruct
}

func NewExampleStructBuilder() *ExampleStructBuilder {
    return &ExampleStructBuilder{}
}

func (b *ExampleStructBuilder) WithDefault() *ExampleStructBuilder {
    b.val.Field0 = "lol"
    b.val.Field8 = ExampleFieldStruct{}
    return b
}

func (b *ExampleStructBuilder) Field0(v string) *ExampleStructBuilder {
    b.val.Field0 = v
    return b
}

func (b *ExampleStructBuilder) Field2(v []string) *ExampleStructBuilder {
    b.val.Field2 = v
    return b
}

func (b *ExampleStructBuilder) Field3(v *string) *ExampleStructBuilder {
    b.val.field3 = v
    return b
}

func (b *ExampleStructBuilder) Field4(v time.Time) *ExampleStructBuilder {
    b.val.field4 = v
    return b
}

func (b *ExampleStructBuilder) Field5(v *time.Time) *ExampleStructBuilder {
    b.val.Field5 = v
    return b
}

func (b *ExampleStructBuilder) Field6(v map[string]string) *ExampleStructBuilder {
    b.val.Field6 = v
    return b
}

func (b *ExampleStructBuilder) Field7(v chan int) *ExampleStructBuilder {
    b.val.Field7 = v
    return b
}

func (b *ExampleStructBuilder) Field8(v ExampleFieldStruct) *ExampleStructBuilder {
    b.val.Field8 = v
    return b
}

func (b *ExampleStructBuilder) Field9(v *ExampleFieldStruct) *ExampleStructBuilder {
    b.val.Field9 = v
    return b
}

func (b *ExampleStructBuilder) Field10(v examplepackage.ExampleTest) *ExampleStructBuilder {
    b.val.Field10 = v
    return b
}

func (b *ExampleStructBuilder) Field11(v *examplepackage.ExampleTest) *ExampleStructBuilder {
    b.val.Field11 = v
    return b
}

func (b *ExampleStructBuilder) Field12(v []examplepackage.ExampleTest) *ExampleStructBuilder {
    b.val.Field12 = v
    return b
}

func (b *ExampleStructBuilder) Field13(v []*examplepackage.ExampleTest) *ExampleStructBuilder {
    b.val.Field13 = v
    return b
}

func (b *ExampleStructBuilder) Field14(v map[ExampleFieldStruct]string) *ExampleStructBuilder {
    b.val.Field14 = v
    return b
}

func (b *ExampleStructBuilder) Field15(v map[examplepackage.ExampleTest]examplepackage.ExampleTest) *ExampleStructBuilder {
    b.val.Field15 = v
    return b
}

func (b *ExampleStructBuilder) Field16(v map[examplepackage.ExampleTest]string) *ExampleStructBuilder {
    b.val.Field16 = v
    return b
}

func (b *ExampleStructBuilder) Field17(v [8]string) *ExampleStructBuilder {
    b.val.Field17 = v
    return b
}

func (b *ExampleStructBuilder) Field18(v func(string) (string, error)) *ExampleStructBuilder {
    b.val.Field18 = v
    return b
}

func (b *ExampleStructBuilder) Build() ExampleStruct {
    return b.val
}
