package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/signal"
	"strings"
	"text/template"
)

var builderHeaderTmpl = template.Must(template.New("builder_header").Parse(`
// Code generated by github.com/ARUMANDESU/gobuildergen. DO NOT EDIT.
package {{.Package}}

{{if eq (len .Imports) 1 -}}
import "{{index .Imports 0}}"
{{else if gt (len .Imports) 1 -}}
import (
{{- range .Imports}}
    "{{.}}"
{{- end}}
)
{{end -}}
`))

var builderBodyTmpl = template.Must(template.New("builder_body").Parse(`

type {{.StructName}}Builder struct {
    val {{.StructName}}
}

func New{{.StructName}}Builder() *{{.StructName}}Builder {
    return &{{.StructName}}Builder{}
}

func (b *{{.StructName}}Builder) WithDefault() *{{.StructName}}Builder {
    {{- range .Fields}}
    {{- if .Default}}
    b.val.{{.Name}} = {{.Default}}
    {{- end}}
    {{- end}}
    return b
}
{{range .Fields}}
func (b *{{$.StructName}}Builder) {{.FuncName}}(v {{.Type}}) *{{$.StructName}}Builder {
    b.val.{{.Name}} = v
    return b
}
{{end}}
func (b *{{.StructName}}Builder) Build() {{.StructName}} {
    return b.val
}
`))

type TemplateHeader struct {
	Package string
	Imports []string
}

type TemplateBody struct {
	StructName string
	Fields     []TemplateStructField
}

type TemplateStructField struct {
	Name     string
	FuncName string
	Type     string
	Default  string
}

func main() {
	ctx := context.Background()
	if err := run(ctx, os.Args, os.Getenv); err != nil {
		fmt.Fprintf(os.Stderr, "%s\n: args: %v", err, os.Args)
		os.Exit(1)
	}
}

func run(ctx context.Context, args []string, getenv func(string) string) error {
	_, cancel := signal.NotifyContext(ctx, os.Interrupt)
	defer cancel()

	fmt.Println(args)
	var typeName string

	flagset := flag.NewFlagSet("run", flag.ExitOnError)

	flagset.StringVar(&typeName, "type", "", "struct type name gobuildergen generating builder for")

	err := flagset.Parse(args[1:])
	if err != nil {
		return fmt.Errorf("flagset failed to parse args: %w", err)
	}

	if typeName == "" {
		return fmt.Errorf("--type must be specified")
	}
	fileName := getenv("GOFILE")
	if fileName == "" {
		return fmt.Errorf("GOFILE is blank")
	}

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, fileName, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("failed to parse dir: %w", err)
	}

	ast.Print(fset, file)
	headerData := TemplateHeader{Package: file.Name.Name}
	bodyData := TemplateBody{StructName: typeName}

	ast.Inspect(file, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok || ts.Name.Name != typeName {
			return true
		}

		fmt.Printf("type spec: %+v\n", ts)
		st, ok := ts.Type.(*ast.StructType)
		if !ok {
			return true
		}

		fmt.Printf("struct type: %+v\n", st)

		for _, field := range st.Fields.List {
			for _, name := range field.Names {
				fmt.Printf("method: %s\n", name.Name)
				bodyData.Fields = append(bodyData.Fields,
					TemplateStructField{
						Name:     name.Name,
						FuncName: strings.ToUpper(name.Name[:1]) + name.Name[1:],
						Type:     "TODO",
						Default:  "TODO",
					})
				// TODO: add into headerData.Imports if there is one
			}
		}
		return false
	})

	var buf bytes.Buffer
	err = builderHeaderTmpl.Execute(&buf, headerData)
	if err != nil {
		return fmt.Errorf("failed to execute header template: %w", err)
	}
	err = builderBodyTmpl.Execute(&buf, bodyData)
	if err != nil {
		return fmt.Errorf("failed to execute body template: %w", err)
	}

	fmt.Println(buf.String())

	return nil
}
