package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"os/signal"
	"strconv"
	"strings"
	"text/template"
)

var builderHeaderTmpl = template.Must(template.New("builder_header").Parse(`// Code generated by github.com/ARUMANDESU/gobuildergen. DO NOT EDIT.
package {{.Package}}

{{if eq (len .Imports) 1 -}}
import {{index .Imports 0}}
{{else if gt (len .Imports) 1 -}}
import (
{{- range .Imports}}
    {{.}}
{{- end}}
)
{{end -}}
`))

var builderBodyTmpl = template.Must(template.New("builder_body").Parse(`
type {{.StructName}}Builder struct {
    val {{.StructName}}
}

func New{{.StructName}}Builder() *{{.StructName}}Builder {
    return &{{.StructName}}Builder{}
}

func (b *{{.StructName}}Builder) WithDefault() *{{.StructName}}Builder {
    {{- range .Fields}}
    {{- if .Default}}
    b.val.{{.Name}} = {{.Default}}
    {{- end}}
    {{- end}}
    return b
}
{{range .Fields}}
func (b *{{$.StructName}}Builder) {{.FuncName}}(v {{.Type}}) *{{$.StructName}}Builder {
    b.val.{{.Name}} = v
    return b
}
{{end}}
func (b *{{.StructName}}Builder) Build() {{.StructName}} {
    return b.val
}
`))

type TemplateHeader struct {
	Package string
	Imports []string
}

type TemplateBody struct {
	StructName string
	Fields     []TemplateStructField
}

type TemplateStructField struct {
	Name     string
	FuncName string
	Type     string
	Default  string
}

func main() {
	ctx := context.Background()
	if err := run(ctx, os.Args, os.Getenv); err != nil {
		fmt.Fprintf(os.Stderr, "%s\n: args: %v", err, os.Args)
		os.Exit(1)
	}
}

func run(ctx context.Context, args []string, getenv func(string) string) error {
	_, cancel := signal.NotifyContext(ctx, os.Interrupt)
	defer cancel()

	var typeName string
	var fileName string

	flagset := flag.NewFlagSet("run", flag.ExitOnError)

	flagset.StringVar(&typeName, "type", "", "struct type name gobuildergen generating builder for")

	err := flagset.Parse(args[1:])
	if err != nil {
		return fmt.Errorf("flagset failed to parse args: %w", err)
	}

	if typeName == "" {
		return fmt.Errorf("--type must be specified")
	}
	fileName = getenv("GOFILE")
	if fileName == "" {
		return fmt.Errorf("GOFILE is blank")
	}

	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, fileName, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("failed to parse dir: %w", err)
	}

	headerData := TemplateHeader{Package: node.Name.Name}
	bodyData := TemplateBody{StructName: typeName}

	imports := make(map[string]string)
	var ts *ast.TypeSpec
	ast.Inspect(node, func(n ast.Node) bool {
		switch t := n.(type) {
		case *ast.TypeSpec:
			if t.Name.Name == typeName {
				ts = t
				return false
			}
		case *ast.ImportSpec:
			name, err := strconv.Unquote(t.Path.Value)
			if err != nil {
				fmt.Printf("failed to unquote: %s\n", err)
				return true
			}
			path := t.Path.Value
			if t.Name != nil {
				name = t.Name.Name
				path = fmt.Sprintf("%s %s", t.Name.Name, t.Path.Value)
			}

			imports[name] = path
		}
		return true
	})

	if ts == nil {
		return fmt.Errorf("no such struct type in this file")
	}

	ast.Inspect(ts, func(n ast.Node) bool {
		se, ok := n.(*ast.SelectorExpr)
		if !ok {
			return true
		}

		expr := se.X.(*ast.Ident)
		if val, ok := imports[expr.Name]; ok {
			headerData.Imports = append(headerData.Imports, val)
			delete(imports, expr.Name)
		}

		return false
	})

	st, ok := ts.Type.(*ast.StructType)
	if !ok {
		return fmt.Errorf("type must be struct")
	}

	for _, field := range st.Fields.List {
		tag, err := ParseTag(field.Tag)
		if err != nil {
			fmt.Printf("failed to parse tag(%s): %s", field.Tag.Value, err)
		}
		if tag.Ignore {
			continue
		}
		for _, name := range field.Names {
			fieldType := types.ExprString(field.Type)
			bodyData.Fields = append(bodyData.Fields,
				TemplateStructField{
					Name:     name.Name,
					FuncName: strings.ToUpper(name.Name[:1]) + name.Name[1:],
					Type:     fieldType,
					Default:  tag.Default,
				})
		}
	}

	var buf bytes.Buffer
	err = builderHeaderTmpl.Execute(&buf, headerData)
	if err != nil {
		return fmt.Errorf("failed to execute header template: %w", err)
	}
	err = builderBodyTmpl.Execute(&buf, bodyData)
	if err != nil {
		return fmt.Errorf("failed to execute body template: %w", err)
	}

	file, err := os.Create(strings.TrimSuffix(fileName, ".go") + "_builder_gen.go")
	if err != nil {
		return fmt.Errorf("failed to open file: %w", err)
	}

	_, err = file.Write(buf.Bytes())
	if err != nil {
		return fmt.Errorf("failed to write buf into file: %w", err)
	}

	return nil
}

type Tag struct {
	Default string
	Ignore  bool
}

func ParseTag(tagBasicLit *ast.BasicLit) (Tag, error) {
	if tagBasicLit == nil || len(tagBasicLit.Value) == 0 {
		return Tag{}, nil
	}

	tag, err := strconv.Unquote(tagBasicLit.Value)
	if err != nil {
		return Tag{}, err
	}

	var builderValue string
	for t := range strings.FieldsSeq(tag) {
		if val, ok := strings.CutPrefix(t, "builder:"); ok {
			val, err := strconv.Unquote(val)
			if err != nil {
				return Tag{}, err
			}

			builderValue = val
		}
	}

	var t Tag
	for option := range strings.SplitSeq(builderValue, ",") {
		option = strings.TrimSpace(option)
		switch option {
		case "-":
			t.Ignore = true
		}

		if key, value, found := strings.Cut(option, "="); found {
			switch key {
			case "default":
				t.Default = value
			}
		}
	}
	return t, nil
}
