package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestBuilderHeaderTmpl(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		data     TemplateHeader
		expected string
	}{
		{
			name: "without imports",
			data: TemplateHeader{
				Package: "test",
			},
			expected: `// Code generated by github.com/ARUMANDESU/gobuildergen. DO NOT EDIT.
package test

`,
		},
		{
			name: "with one import",
			data: TemplateHeader{
				Package: "test",
				Imports: []string{"\"time\""},
			},
			expected: `// Code generated by github.com/ARUMANDESU/gobuildergen. DO NOT EDIT.
package test

import "time"
`,
		},
		{
			name: "with many imports",
			data: TemplateHeader{
				Package: "test",
				Imports: []string{"\"time\"", "\"bytes\""},
			},
			expected: `// Code generated by github.com/ARUMANDESU/gobuildergen. DO NOT EDIT.
package test

import (
    "time"
    "bytes"
)
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			var buf bytes.Buffer
			err := builderHeaderTmpl.Execute(&buf, tt.data)
			require.NoError(t, err)
			assert.Equal(t, tt.expected, buf.String())
		})
	}
}

func TestBuilderBodyTmpl(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		data     TemplateBody
		expected string
	}{
		{
			name: "test",
			data: TemplateBody{
				StructName: "Test",
				Fields: []TemplateStructField{
					{Name: "TestField1", FuncName: "TestField1", Type: "string", Default: "\"lol\""},
					{Name: "TestField2", FuncName: "TestField2", Type: "string"},
					{Name: "TestField3", FuncName: "TestField3", Type: "int", Default: "16"},
					{Name: "testField4", FuncName: "TestField4", Type: "string"},
				},
			},
			expected: `
type TestBuilder struct {
    val Test
}

func NewTestBuilder() *TestBuilder {
    return &TestBuilder{}
}

func (b *TestBuilder) WithDefault() *TestBuilder {
    b.val.TestField1 = "lol"
    b.val.TestField3 = 16
    return b
}

func (b *TestBuilder) TestField1(v string) *TestBuilder {
    b.val.TestField1 = v
    return b
}

func (b *TestBuilder) TestField2(v string) *TestBuilder {
    b.val.TestField2 = v
    return b
}

func (b *TestBuilder) TestField3(v int) *TestBuilder {
    b.val.TestField3 = v
    return b
}

func (b *TestBuilder) TestField4(v string) *TestBuilder {
    b.val.testField4 = v
    return b
}

func (b *TestBuilder) Build() Test {
    return b.val
}
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			var buf bytes.Buffer
			err := builderBodyTmpl.Execute(&buf, tt.data)
			require.NoError(t, err)
			assert.Equal(t, tt.expected, buf.String())
			fmt.Println(buf.String())
		})
	}
}

func TestParseTag(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		tag      *ast.BasicLit
		extected Tag
	}{
		{
			name:     "no tags: nil",
			extected: Tag{},
		},
		{
			name:     "no tags: empty string",
			tag:      &ast.BasicLit{Value: ""},
			extected: Tag{},
		},
		{
			name:     "no tags: for builder",
			tag:      &ast.BasicLit{Value: "`json:\"test\"`"},
			extected: Tag{},
		},
		{
			name:     "no tags: empty builder",
			tag:      &ast.BasicLit{Value: "`builder:\"\"`"},
			extected: Tag{},
		},
		{
			name:     "default tag",
			tag:      &ast.BasicLit{Value: "`builder:\"default=\\\"test\\\"\"`"},
			extected: Tag{Default: "\"test\""},
		},
		{
			name:     "ignore tag",
			tag:      &ast.BasicLit{Value: "`builder:\"-\"`"},
			extected: Tag{Ignore: true},
		},
		{
			name:     "default, ignore tag",
			tag:      &ast.BasicLit{Value: "`builder:\"default=\\\"test\\\",-\"`"},
			extected: Tag{Default: "\"test\"", Ignore: true},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			tag, err := ParseTag(tt.tag)
			require.NoError(t, err)

			assert.Equal(t, tt.extected, tag)
		})
	}
}
