package main

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestBuilderTmpl(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		data     TemplateData
		expected string
	}{
		{
			name: "without imports",
			data: TemplateData{
				Package: "test",
			},
			expected: `
// Code generated by github.com/ARUMANDESU/gobuildergen. DO NOT EDIT.
package test

`,
		},
		{
			name: "with one import",
			data: TemplateData{
				Package: "test",
				Imports: []string{"time"},
			},
			expected: `
// Code generated by github.com/ARUMANDESU/gobuildergen. DO NOT EDIT.
package test

import "time"
`,
		},
		{
			name: "with many imports",
			data: TemplateData{
				Package: "test",
				Imports: []string{"time", "bytes"},
			},
			expected: `
// Code generated by github.com/ARUMANDESU/gobuildergen. DO NOT EDIT.
package test

import (
    "time"
    "bytes"
)
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var buf bytes.Buffer
			err := builderTmpl.Execute(&buf, tt.data)
			require.NoError(t, err)
			assert.Equal(t, tt.expected, buf.String())
		})
	}
}
